
<link rel="stylesheet" href="/Users/roobadi/Desktop/github/JS01Anaiya/STYLES/styles.css">

var wasssup = function (name) {
    console.log("wassup,"+" "+"name");
};
wassup("peeps");

var wassup = function (name) {
  console.log ("wassup"+" "+"name");
};
wassup("Mama");

var wassup = function (name) {
  console.log ("wassup"+" "+"name");
};
wassup ("ma");

var wassup = function (name) {
  console.log ("wassup"+" "+"name");
};
wassup ("mamsters");

var wassup = function (name) {
  console.log("wassup"+" "+"name");
};
